name: Build and Publish OpenMRS
on:
  push:
    branches: [master]

jobs:
  docker-build-publish:
    name: DDownload Torrent 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install
        run: echo "CLUSTER_NAME=jfjdfdf" >> $GITHUB_ENV
      - name: Download 
        run: echo $CLUSTER_NAME
